// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClMfH1QDOzKj5D4yYsgkTacxXe0c42DpQ',
    appId: '1:382981048379:web:3859d9ec8b5e90d057b41e',
    messagingSenderId: '382981048379',
    projectId: 'mtestapp-8218a',
    authDomain: 'mtestapp-8218a.firebaseapp.com',
    storageBucket: 'mtestapp-8218a.firebasestorage.app',
    measurementId: 'G-93XJSTLS70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBdNsqU0E6f-mtohNcxzWhQVjDo4t4Pgs',
    appId: '1:382981048379:android:7b69c8ab8fe2849b57b41e',
    messagingSenderId: '382981048379',
    projectId: 'mtestapp-8218a',
    storageBucket: 'mtestapp-8218a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhA95bhPOWWtzR0yv5r_rdjeZL4MYj2QE',
    appId: '1:382981048379:ios:24d8773b2091ebd757b41e',
    messagingSenderId: '382981048379',
    projectId: 'mtestapp-8218a',
    storageBucket: 'mtestapp-8218a.firebasestorage.app',
    iosBundleId: 'com.example.testEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhA95bhPOWWtzR0yv5r_rdjeZL4MYj2QE',
    appId: '1:382981048379:ios:24d8773b2091ebd757b41e',
    messagingSenderId: '382981048379',
    projectId: 'mtestapp-8218a',
    storageBucket: 'mtestapp-8218a.firebasestorage.app',
    iosBundleId: 'com.example.testEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClMfH1QDOzKj5D4yYsgkTacxXe0c42DpQ',
    appId: '1:382981048379:web:f915a0e5639200b957b41e',
    messagingSenderId: '382981048379',
    projectId: 'mtestapp-8218a',
    authDomain: 'mtestapp-8218a.firebaseapp.com',
    storageBucket: 'mtestapp-8218a.firebasestorage.app',
    measurementId: 'G-DPKYW111D0',
  );

}